version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    build:
      context: .
      dockerfile: mysql_dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=1q2w3e
      - MYSQL_USER=cgp
    ports:
      - 3306:3306
  spring-boot-jpa-docker-webapp:
    build:
      context: .
      dockerfile: DockerFile
    image: tema2
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=cgp
      - DATABASE_PASSWORD=1q2w3e
      - DATABASE_NAME=test  
      - DATABASE_PORT=3306